language: node_js
services:
  - mongodb
node_js:
  - "12"
  - "10"
  - "8"
  - "6"
before_script:
  - npm install
notifications:
  email:
    - vic@smalldata.tech
# This does not work because nyc uses async functions which are not supported on Node 6.
#script:
#  - npm run test:travis
